### ISSUE TITLE
Tekst wychodzi poza granice menu

### ISSUE THREAD

**Issue by VeryLongNicknameSuchWow** [programmerpeter/MinecraftServerManager#1]
http://screenshot.sh/n8jLUSmbTUefZ
Tak to mniej więcej wygląda, nie wiem czy to wina tego że program był odpalony na linuksie za pomocą wine, ale mówię jak jest :)

**Comment by Libter** [comment]
W kolejnej wersji (0.7.1) szerokość elementu menu będzie automatycznie dostosowywać się do szerokości tekstu - powinno to naprawić ten problem.

**Comment by Libter** [comment]
Wersja 0.7.1 wydana - problem został naprawiony.
Dziękuję bardzo za napisanie tego zgłoszenia i zachęcam do raportowania kolejnych bugów.
Zamykam.
